version: "3.8"

services:
  app:
    image: khai1301/matching_system:latest
    container_name: matching_system_app
    volumes:
      - ./.env:/var/www/.env
      - app-storage:/var/www/storage
      - app-cache:/var/www/bootstrap/cache
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: matching_system_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app-storage:/var/www/storage:ro
      - app-cache:/var/www/bootstrap/cache:ro
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  app-storage:
  app-cache: